config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }, sign_out_via: [:get, :post]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "splashs#index"
  get 'confirm', to: 'splashs#confirmation'
  resources :categories
  resources :expenses
end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # validates :name, presence: true, allow_blank: false
  validates :name, presence: true, uniqueness: { scope: :user_id }

  has_many :expenses, foreign_key: :category_id, dependent: :destroy
  belongs_to :user, class_name: 'User'

  has_one_attached :image

  def image_as_thumbnail
    image.variant(resize_to_limit: [50, 50]).processed
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
  # Validation
  validates :name, presence: true, allow_blank: false
  validates :amount, presence: true, allow_blank: false
  validates :category_id, presence: true, allow_blank: false
  # validates :date_of_expense, presence: true, allow_blank: false

  belongs_to :user, class_name: 'User'
  belongs_to :category, class_name: 'Category'

  # rubocop:disable Style/FormatString
  def amount
    '₦%.2f' % self[:amount] if self[:amount]
  end
  # rubocop:enable Style/FormatString
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  validates :name, presence: true, allow_blank: false

  has_many :expenses, foreign_key: :user_id, dependent: :destroy
  has_many :categories, foreign_key: :user_id, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmable)
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @expenses = @category.expenses.where(user_id: current_user.id).order(:created_at)
    @total = @expenses.sum(:amount)
  end

  private

  def category_params
    params.require(:category).permit(:name, :image)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog, only: %i[show edit update destroy]

  def index; end

  def new
    @expense = Expense.new
    @categories = Category.where(user_id: current_user.id).order(:name)
  end

  def show
    @expense = Expense.find(params[:id])
    @categories = @expense.category
  end

  def create
    @expense = Expense.new(expense_params)
    @categories = Category.where(user_id: current_user.id).order(:name)
    @expense.user_id = current_user.id
    if @expense.save
      # redirect_to categories_path
      redirect_to category_path(@expense.category_id)
    else
      render template: 'expenses/new'
      # render :new
    end
  end

  def edit; end

  def update
    if @expense.update(expense_params)
      redirect_to @expense
    else
      render :edit
    end
  end

  def destroy
    @expense.destroy
    redirect_to expenses_path
  end

  private

  def expense_params
    # params.require(:expense).permit(:name, :amount, :date_of_expense, categories: []) //Multiple Cat
    params.require(:expense).permit(:name, :amount, :date_of_expense, :category_id)
  end

  def set_blog
    @expense = Expense.find(params[:id])
    @categories = Category.where(user_id: current_user.id).order(:name)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(_resource)
    confirm_path
  end

  def after_inactive_sign_up_path_for(_resource)
    confirm_path
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/splashs_controller.rb
class SplashsController < ApplicationController
  def index; end

  def confirmation
    render template: 'splashs/confirmation'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_with(model: @category) do |f|  %>

<p>
<%= f.label :name %><br/>
<%= f.text_field :name, placeholder: 'Category Name', class: 'form-control' %>
</p>

<p>
<%= f.label :image %><br/>
<%= f.file_field :image, class: 'form-control' %>
</p>

 <div class="d-grid gap-2 paddingspace">
<%= f.submit(@category.new_record? ? "Add" : "Update", class: 'buttonpadd btn-lg btn-down-color') %>
</div>

<% end %>

app/views/categories/index.html.erb
<div class="main_splash">
<div class="box">
    <div class="top-heading">
       <a href="/"><i class="fa-solid fa-bars bar-align"></i></a>
        <h5>Expense Categories</h5>
    </div>

    <div class="content-area">

    <% @categories.each do |cat|  %>

    <div class="mainArea">
        <%# <div class="mainImage"><%= image_tag(cat.image) %>
         <div class="mainImage"><%= link_to image_tag(cat.image_as_thumbnail), cat.image if cat.image.attached? %></div>
        
       
        <div class="mainContentArea">
            <div class="mainTitle"> <a href="/categories/<%= cat.id %>"><h6><%= cat.name %> </h6></a></div>
            <div class="mainDescription"><span style="font-size:11px"><%= cat.created_at.strftime("%Y-%m-%d") %></span></div>
        </div>
        <div class="mainDescription">
            ₦<%= number_with_delimiter(cat.expenses.sum(:amount)) %>
        </div>
    </div>
    <%# <span>&nbsp;</span> %>
    <% end %>

        <div class="d-grid gap-2">
         <%= link_to "Add Category", new_category_path, class: 'buttonpadd btn-lg btn-down-color' %>
          
        </div>

    </div>

</div>
</div>

app/views/categories/new.html.erb
<div class="main_splash">
<div class="box">
<div class="top-heading">

 <a href="/categories"><i class="fa-solid fa-backward"></i></a>
 <h5>Add Category</h5>
</div>

<div class="content-area">
    <%= render 'form' %>
</div>
</div>
</div>

app/views/categories/show.html.erb
<div class="main_splash">
<div class="box">
<div class="top-heading">
 <a href="/categories"><i class="fa-solid fa-backward"></i></a>
 <h5><%= @category.name.upcase %> CATEGORY EXPENSE </h5>

</div>
 <div class="badge-success expensetotal">Total Expense Amount  ₦<%= number_with_delimiter(@total) %></div>
 <div class="clearboth"></div>
<div class="content-area">

   <% @expenses.each do |exp| %>

    <div class="mainArea">
        
        <div class="mainContentArea">
            <div class="mainTitle"> <a href="/expenses/<%= exp.id %>"><h6><%= exp.name %> </h6></a></div>
            <div class="mainDescription"><span style="font-size:11px"><%= exp.date_of_expense.strftime("%Y-%m-%d") %></span></div>
        </div>
        <div class="mainDescription"><%= exp.amount %></div>
    </div>
   <% end %>
  

    <div class="d-grid gap-2">
     <%= link_to "Add Expense", new_expense_path, class: 'buttonpadd btn-lg btn-down-color' %>
    </div>
</div>
</div>
</div>

app/views/expenses/_form.html.erb
<%= render 'shared/errors', obj: @expense %>

<%= form_with(model: @expense) do |f|  %>

<p>
<%= f.label :date %><br/>
<%= f.date_field :date_of_expense, :class => "form-control" %>
<p>

<%= f.label :name %><br/>
<%= f.text_field :name, placeholder: 'Add Expense Name', class: 'form-control' %>
</p>

<p>
<%= f.label :amount %><br/>
<%= f.number_field :amount, class: 'form-control' %>
</p>

<p>
<%= f.label :category %><br/>
  <%= f.select :category_id, @categories.map { |category| [category.name, category.id] }, {:required => true, include_hidden: false, include_blank: ' select '}, {:class => 'form-control', :multiple => false} %>
<!--<select class="form-control">
    <%= @categories.each do |cat| %>
        <option value="<%= cat.id %>"><%= cat.name %></option>
     <% end %>
    </select>-->
</p>

 <div class="d-grid gap-2 paddingspace">
<%= f.submit(@expense.new_record? ? "Add Expense" : "Update Expense", class: 'buttonpadd btn-lg btn-down-color') %>
</div>

<% end %>

app/views/expenses/edit.html.erb
<div class="main_splash">
<div class="box">
<div class="top-heading">
<i class="bi bi-credit-card" aria-hidden="true"></i>
 <h3>Edit Expense</h3>
</div>

<div class="content-area">
    <%= render 'form' %>
</div>
</div>
</div>

app/views/expenses/index.html.erb
<div class="main_splash">
<div class="box">
    <div class="top-heading">
        <h3>ALL EXPENSE</h3>
    </div>

    <div class="content-area">

        <div class="d-grid gap-2">
           

        <div class="d-grid gap-2">
         <%= link_to "Add Expense", new_expense_path, class: 'buttonpadd btn-lg btn-down-color' %>
          
        </div>

    </div>

</div>
</div>

app/views/expenses/new.html.erb
<div class="main_splash">
<div class="box">
<div class="top-heading">
<i class="bi bi-credit-card" aria-hidden="true"></i>
 <h3>Add New Expense</h3>
</div>

<div class="content-area">
    <%= render 'form' %>
</div>
</div>
</div>

app/views/expenses/show.html.erb
<div class="main_splash">
<div class="box">
<div class="top-heading">
 <a href="/categories/<%= @categories.id %>"><i class="fa-solid fa-backward"></i></a>
 <h5>Expenses Details</h5>
</div>

<div class="content-area">

<div class="mainAreaX">

    <div class="mainImage">
    <center><%= link_to image_tag(@categories.image_as_thumbnail), @categories.image if @categories.image.attached? %></center>
    </div>
    <div class="mainContentArea">
    <div class="mainTitle"> 
    <span style="font-size:9px"><%= @expense.created_at.strftime("%Y-%m-%d") %></span>
    <h3><%= @expense.name.upcase %> </h3>
    </div>
    <div class="mainDescription"><span style="font-size:11px">Amount</span></div>
    </div>
    <div class="mainDescription"><%= @expense.amount %></div><br/>

     <div class="mainDescription"><span style="font-size:11px">Category</span></div>
    <div class="mainDescription"><%= @categories.name %></div>

</div>
  

<div>
 <%= link_to "Edit Expense", edit_expense_path(@expense), class: "btn btn-color" %>
 <%= link_to "Delete Expense", expense_path(@expense), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
</div>
</div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.css"/>
   
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    
  </head>

  <body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div>
        <h6 class="bg bg-danger">The following errors prevented the <%= obj.class.name.downcase %> from being saved:</h6>
        <%# <%= pluralize(@blog.errors.count, "error") %> 
        <%# prohibited this blog from being saved:  %>
        </h2>
        <ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/splashs/confirmation.html.erb
<div class="main_splash">
<div class="box">
 <center><div class="bg bg-success">Thank you for registration with us. Please check your email to activate your account.<div></center>
    <h2>Budget Tracker</h2>
    
     <div class="d-grid gap-2 paddingspace">
    
        <a href="users/sign_in"  class="btn btn-md btn-color">Login</a>
    </div>

    

</div>
</div>

app/views/splashs/index.html.erb
<div class="main_splash">

 

<div class="box">
 <% if user_signed_in? %>
    <span class="pushright">Welcome <%= current_user.name.upcase %></span>
    <span class="clearboth"></span>
<% end %>
    <h2 class="pushcenter">Budget Tracker</h2>
       
    
        <%# <a href="users/sign_in"  class="btn btn-md btn-color">Login</a>
        <a href="users/sign_up"  class="btn btn-md btn-default">Signup</a> %>
    
<div class="d-grid gap-2 paddingspace">
    <% if user_signed_in? %>
     <a href="categories"  class="btn btn-md btn-primary">Categories</a>
     <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-md btn-danger'  %>
    
    <% else %>
       <a href="users/sign_in"  class="btn btn-md btn-color">Login</a>
        <a href="users/sign_up"  class="btn btn-md btn-default">Signup</a>
    <% end %>
    </div>

</div>
</div>
